<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LowlandTech.Foundry.PluginCore\LowlandTech.Foundry.PluginCore.csproj" />
    <ProjectReference Include="..\LowlandTech.Foundry.SamplePlugin\LowlandTech.Foundry.SamplePlugin.csproj" />
    <ProjectReference Include="..\LowlandTech.Foundry.PremiumTheme\LowlandTech.Foundry.PremiumTheme.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
