<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LowlandTech.Foundry.P2P.Core\LowlandTech.Foundry.P2P.Core.csproj" />
    <ProjectReference Include="..\LowlandTech.Foundry.P2P.Crdt\LowlandTech.Foundry.P2P.Crdt.csproj" />
  </ItemGroup>

</Project>
